"""seond

Revision ID: 685b02879deb
Revises: 9781cbe5ad2b
Create Date: 2023-08-22 12:55:58.333192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685b02879deb'
down_revision = '9781cbe5ad2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.SmallInteger(), nullable=False, foreign_key=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_column('id_empresa')

    # ### end Alembic commands ###
