"""cambio longitud telefono

Revision ID: 7b1f42fa85c5
Revises: be8577ad4b7d
Create Date: 2023-09-11 08:49:52.026472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1f42fa85c5'
down_revision = 'be8577ad4b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
