"""tabla empresas

Revision ID: 84354aa97463
Revises: 9781cbe5ad2b
Create Date: 2023-08-23 09:41:03.776043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84354aa97463'
down_revision = '9781cbe5ad2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('cod_empresa', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cod_empresa')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_cod', sa.SmallInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_cod'], ['cod_empresa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_cod')

    op.drop_table('empresas')
    # ### end Alembic commands ###
