"""tabla direcciones

Revision ID: 94a512ddca30
Revises: 84354aa97463
Create Date: 2023-08-23 15:10:28.662127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a512ddca30'
down_revision = '84354aa97463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('cod_direccion', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('zona', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('persona_cod', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['persona_cod'], ['personas.cod_persona'], ),
    sa.PrimaryKeyConstraint('cod_direccion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direcciones')
    # ### end Alembic commands ###
