"""tabla roles

Revision ID: ad20add9a76f
Revises: cf10881f1853
Create Date: 2023-10-03 11:24:15.695450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad20add9a76f'
down_revision = 'cf10881f1853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('usuario_creador', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('usuario_editor', sa.String(length=50), nullable=True))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('usuario_editor')
        batch_op.drop_column('usuario_creador')
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
